// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbvrcndcyjowytgfmvop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJidnJjbmRjeWpvd3l0Z2Ztdm9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUyMDc4NjgsImV4cCI6MjA5MDc4Mzg2OH0.hh_r7nJZ4Su8RGxYDbjm2feYNkbUkwwiu_INs5R2_XQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});